### ISSUE TITLE
[VL] Spark 4.1: Compile error with spark 4.1

### ISSUE THREAD

**Issue by Yao-MR** [oap-project/gluten#11969]
### Backend

VL (Velox)

### Bug description

compile command:

./dev/buildbundle-veloxbe.sh  --spark_version=4.1

### Gluten version

master branch

### Spark version

4.1

### System information

env:
  os: ubuntu
  java: 17
  scala: 2.13
  spark: 4.1

### Relevant logs

```bash
[INFO] --- scala:4.9.5:add-source (scala-compile-first) @ gluten-core ---
[INFO] Add Source directory: /data1/community/incubator-gluten/gluten-core/src/main/scala
[INFO] Add Test Source directory: /data1/community/incubator-gluten/gluten-core/src/test/scala
[INFO] 
[INFO] --- scala:4.9.5:compile (scala-compile-first) @ gluten-core ---
[INFO] /data1/community/incubator-gluten/gluten-core/src/main/java:-1: info: compiling
[INFO] /data1/community/incubator-gluten/gluten-core/target/generated-sources/protobuf/java:-1: info: compiling
[INFO] /data1/community/incubator-gluten/gluten-core/src/main/scala:-1: info: compiling
[INFO] Compiling 116 source files to /data1/community/incubator-gluten/gluten-core/target/scala-2.13/classes at 1776748484794
[INFO] compiler plugin: BasicArtifact(org.wartremover,wartremover_2.13,3.2.0,null)
[ERROR] scalac error: '1.8' is not a valid choice for '-release'
[INFO]   scalac -help  gives more information
[ERROR] scalac error: bad option: '-release'
[INFO]   scalac -help  gives more information
[ERROR] exception compilation error occurred!!!
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:355)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:253)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:236)
    at scala_maven_executions.JavaMainCallerByFork.run (JavaMainCallerByFork.java:95)
    at scala_maven.ScalaCompilerSupport.compile (ScalaCompilerSupport.java:173)
    at scala_maven.ScalaCompilerSupport.doExecute (ScalaCompilerSupport.java:86)
    at scala_maven.ScalaMojoSupport.execute (ScalaMojoSupport.java:310)
    at scala_maven.ScalaCompileMojo.execute (ScalaCompileMojo.java:108)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:328)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:316)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:212)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:174)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:75)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:162)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:159)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:919)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:285)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:207)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:569)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:314)
[INFO] prepare-compile in 0.0 s
[INFO] compile in 0.6 s
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Gluten Parent Pom 1.7.0-SNAPSHOT:
[INFO] 
[INFO] Gluten Parent Pom .................................. SUCCESS [  2.129 s]
[INFO] Gluten Core ........................................ FAILURE [ 12.537 s]
[INFO] Gluten Shims ....................................... SKIPPED
[INFO] Gluten Shims Common ................................ SKIPPED
[INFO] Gluten Shims for Spark 4.1 ......................... SKIPPED
[INFO] Gluten UI .......................................... SKIPPED
[INFO] Gluten Substrait ................................... SKIPPED
[INFO] Gluten Arrow ....................................... SKIPPED
[INFO] Gluten Backends Velox .............................. SKIPPED
[INFO] Gluten Package ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.990 s
[INFO] Finished at: 2026-04-21T13:14:45+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.9.5:compile (scala-compile-first) on project gluten-core: scala compilation failed -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :gluten-core
```
