### PR TITLE
[CORE] Remove remaining Spark 3.2 compatibility code

### LINKED ISSUE #11379: Remove remaining Spark 3.2-specific compatibility code
### Description

Some Spark 3.2-specific compatibility code remains in the common codebase:
#gluten-core/src/main/scala/org/apache/spark/util/SparkVersionUtil.scala
Defines lteSpark32 (used by other files)
#gluten-core/src/main/scala/org/apache/spark/util/SparkTaskUtil.scala
Lines 67-82: Spark 3.2-specific constructor path for TaskContext
#gluten-core/src/main/scala/org/apache/spark/util/SparkPlanUtil.scala
Lines 26-28: Spark 3.2-specific path for supportsRowBased
#gluten-core/src/main/scala/org/apache/spark/sql/execution/adaptive/GlutenCostEvaluator.scala
Lines 33-35: Spark 3.2-specific CostEvaluator instantiation
#gluten-core/src/main/scala/org/apache/gluten/extension/columnar/transition/Convention.scala
Lines 174-184: Spark 3.2-specific row type handling
#backends-velox/src/test/scala/org/apache/gluten/execution/MiscOperatorSuite.scala
Lines 911-919: Test that checks for Spark 3.2

These items are compatibility shims in shared code that can be cleaned up separately.
Related Issue: #8960 

### Gluten version

None

### PR DESCRIPTION
**Pull request by QCLyu**
## Summary
- Remove all `lteSpark32` branches from shared code (dead code since Spark 3.2 is no longer supported)
- Clean up `SparkVersionUtil.scala` (remove `lteSpark32`, `lteSpark33`)
- Delete orphaned `shims/spark32/` files and Spark 3.2-specific test branches
- Rename `KnownRowTypeForSpark33OrLater` to `KnownRowTypeWithDefault`

## Test plan
- Build with Spark 3.3, 3.4, 3.5 profiles to verify no compilation errors
- Run existing unit tests (no behavioral changes, only dead code removal)

Partially assisted by Claude Opus 4.6.

Closes #11379

### CODE REVIEW

**Comment by QCLyu** [comment]
Hi @PHILO-HE , just thought carefully about your comment in the previous PR: https://github.com/apache/incubator-gluten/pull/11495#discussion_r2740180164 This time I renamed KnownRowTypeForSpark33OrLater to KnownRowTypeWithDefault, instead of completely merging it with KnownRowType.

My rationale is "this: SparkPlan =>" created a self-type constraint: If you put this on KnownRowType directly, then any implementor of KnownRowType would have to be a SparkPlan. 

Please correct me if I'm wrong.

**Comment by philo-he** [comment]
> Hi @PHILO-HE , just thought carefully about your comment in the previous PR: [#11495 (comment)](https://github.com/apache/incubator-gluten/pull/11495#discussion_r2740180164) This time I renamed KnownRowTypeForSpark33OrLater to KnownRowTypeWithDefault, instead of completely merging it with KnownRowType.
> 
> My rationale is "this: SparkPlan =>" created a self-type constraint: If you put this on KnownRowType directly, then any implementor of KnownRowType would have to be a SparkPlan. 
> 
> Please correct me if I'm wrong.

@QCLyu, the constraint is acceptable maybe. This trait was introduced to categorize Spark Plans based on the data format. So I would advise merging them. Thanks.

**Comment by QCLyu** [comment]
@PHILO-HE could you please review this PR? 
[One test](https://github.com/apache/gluten/actions/runs/22937015068/job/66571370400?pr=11731) failed because Query q64 did not have enough memory to build and broadcast the table to all worker nodes. Looks irrelevant.
cc @zhouyuan
