### PR TITLE
[CORE] Deprecate and remove Spark 3.2 support

### LINKED ISSUE #8960: [VL] deprecated Spark-3.2 unit tests
### Description

Gluten will gradually deprecate Spark-3.2 support. Discussions in below link:
https://lists.apache.org/thread/fgnv7v5sf9ol14lkssd9v47h6cvorcxc

### PR DESCRIPTION
**Pull request by QCLyu**
## What changes are proposed in this pull request?

This PR comprehensively removes Spark 3.2 support from the Gluten Velox backend. It cleans up the source code, build profiles, CI/CD pipelines, and documentation.

Key changes include:

- Source Code: Removed shims/spark32 and gluten-ut/spark32 directories.

- Build System: Deleted the spark-3.2 profile from the root and all sub-module pom.xml files.

- CI/CD: Removed legacy Spark 3.2 jobs (spark-test-spark32, spark-test-spark32-slow) from GitHub Workflows.

- Test Migration: Refactored VeloxHashJoinSuite and other backend tests to remove Spark 3.2-specific conditional logic, ensuring these tests now run on Spark 3.3+.

- Documentation: Updated the build guide and ClickHouse deployment docs to remove references to Spark 3.2.

## How was this patch tested?

- Manual Build: Verified successful compilation on aarch64 (ARM64) using -Pspark-3.5 -Pbackends-velox.

- Unit Tests: Verified that migrated tests in VeloxHashJoinSuite pass successfully under Spark 3.5.

- CI: Infrastructure changes have been validated to ensure remaining Spark versions (3.3, 3.4, 3.5) trigger correctly.

Closes #8960

### CODE REVIEW

**Comment by QCLyu** [comment]
I have verified the changes for Spark 3.5 locally, while GitHub Actions was showing failures:

### Jenkins (ClickHouse CI): SUCCESS. 

The Reactor Summary confirms all modules (including gluten-core, shims, and backends-clickhouse) built successfully and all 36 tests passed.
<details>
<summary>Click to view Jenkins Reactor Summary (Build Success)</summary>

12:33:20  Run completed in 2 minutes, 25 seconds.
12:33:20  Total number of tests run: 36
12:33:20  Suites: completed 2, aborted 0
12:33:20  Tests: succeeded 36, failed 0, canceled 0, ignored 12, pending 0
12:33:20  All tests passed.
12:33:21  [INFO] ------------------------------------------------------------------------
12:33:21  [INFO] Reactor Summary for Gluten Parent Pom 1.6.0-SNAPSHOT:
12:33:21  [INFO]
12:33:21  [INFO] Gluten Parent Pom .................................. SUCCESS [ 17.421 s]
12:33:21  [INFO] Gluten Ras ......................................... SUCCESS [ 23.776 s]
12:33:21  [INFO] Gluten Ras Common .................................. SUCCESS [ 51.164 s]
12:33:21  [INFO] Gluten Core ........................................ SUCCESS [ 37.484 s]
12:33:21  [INFO] Gluten Shims ....................................... SUCCESS [  0.260 s]
12:33:21  [INFO] Gluten Shims Common ................................ SUCCESS [  6.371 s]
12:33:21  [INFO] Gluten Shims for Spark 3.3 ......................... SUCCESS [ 13.796 s]
12:33:21  [INFO] Gluten UI .......................................... SUCCESS [  4.449 s]
12:33:21  [INFO] Gluten Substrait ................................... SUCCESS [ 59.459 s]
12:33:21  [INFO] Gluten Celeborn .................................... SUCCESS [  4.854 s]
12:33:21  [INFO] Gluten Iceberg ..................................... SUCCESS [ 11.367 s]
12:33:21  [INFO] Gluten DeltaLake ................................... SUCCESS [  9.760 s]
12:33:21  [INFO] Gluten Package ..................................... SUCCESS [  6.663 s]
12:33:21  [INFO] Gluten Ras Planner ................................. SUCCESS [  1.137 s]
12:33:21  [INFO] Gluten Kafka ....................................... SUCCESS [  9.403 s]
12:33:21  [INFO] Gluten Backends ClickHouse ......................... SUCCESS [59:48 min]
12:33:21  [INFO] Gluten Unit Test Parent ............................ SUCCESS [  1.323 s]
12:33:21  [INFO] Gluten Unit Test Common ............................ SUCCESS [  5.468 s]
12:33:21  [INFO] Gluten Unit Test ................................... SUCCESS [ 16.964 s]
12:33:21  [INFO] Gluten Unit Test Spark33 ........................... SUCCESS [02:45 min]
12:33:21  [INFO] ------------------------------------------------------------------------
12:33:21  [INFO] BUILD SUCCESS
12:33:21  [INFO] ------------------------------------------------------------------------
12:33:21  [INFO] Total time:  01:07 h
12:33:21  [INFO] Finished at: 2026-01-04T04:33:21Z
12:33:21  [INFO] ------------------------------------------------------------------------


</details>

### GitHub Actions: 

These jobs are failing with 403 Forbidden errors during dependency resolution (Log4j, ASM, etc.). In the following commit, these issues are found and fixed:

* .github/workflows/velox_nightly.yml (2 occurrences)
Removed mvn clean install -Pspark-3.2 from both the x86 and arm64 build jobs
Lines 103 and 226
* .github/workflows/build_bundle_package.yml
Updated description from 'Spark version: spark-3.2, spark-3.3, spark-3.4 or spark-3.5' to 'Spark version: spark-3.3, spark-3.4, spark-3.5 or spark-4.0'
* .github/workflows/util/install-spark-resources.sh
Removed the Spark 3.2 case (lines 92-96) from the script

These changes aim to resolve the 403 errors. The workflows will no longer attempt to build with the removed Spark 3.2 profile.

**Comment by QCLyu** [comment]
Hi @zhouyuan , the code changes here look good. The only ClickHouse CI failure is due to the Jenkins job still running -Pspark-3.2 on Java 8, but this repo no longer has a spark-3.2 profile and pulls Iceberg artifacts built for Java 11 (class version 55). That mismatch causes the compile error in gluten-iceberg. This is a CI config issue, not a code regression. 

Please proceed with merge if everything else looks good to you, and we can update/disable the Spark 3.2 Java 8 leg in the Jenkins pipeline separately.

This is the only failed step in ClickHouse CI: https://opencicd.kyligence.com/job/gluten/job/gluten-ci/18337/flowGraphTable/
This is the log: https://opencicd.kyligence.com/job/gluten/job/gluten-ci/18337/execution/node/235/log/
```text
18:00:32  [ERROR] COMPILATION ERROR : 
18:00:32  [INFO] -------------------------------------------------------------
18:00:32  [ERROR] /home/jenkins/agent/workspace/gluten/gluten-ci/ut-stage-1/gluten-iceberg/src/main/java/org/apache/gluten/connector/write/MetricsWrapper.java:[21,25] error: cannot access Metrics
18:00:32    bad class file: /root/.m2/repository/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.10.0/iceberg-spark-runtime-3.5_2.12-1.10.0.jar(org/apache/iceberg/Metrics.class)
18:00:32      class file has wrong version 55.0, should be 52.0
18:00:32      Please remove or make sure it appears in the correct subdirectory of the classpath.
18:00:32  [INFO] 1 error
18:00:32  [INFO] -------------------------------------------------------------
18:00:32  [INFO] ------------------------------------------------------------------------
18:00:32  [INFO] Reactor Summary for Gluten Parent Pom 1.6.0-SNAPSHOT:
18:00:32  [INFO] 
18:00:32  [INFO] Gluten Parent Pom .................................. SUCCESS [ 21.426 s]
18:00:32  [INFO] Gluten Ras ......................................... SUCCESS [ 22.345 s]
18:00:32  [INFO] Gluten Ras Common .................................. SUCCESS [ 51.109 s]
18:00:32  [INFO] Gluten Core ........................................ SUCCESS [ 39.051 s]
18:00:32  [INFO] Gluten Shims ....................................... SUCCESS [  0.336 s]
18:00:32  [INFO] Gluten Shims Common ................................ SUCCESS [  6.173 s]
18:00:32  [INFO] Gluten Shims for Spark 3.5 ......................... SUCCESS [ 12.425 s]
18:00:32  [INFO] Gluten UI .......................................... SUCCESS [  5.105 s]
18:00:32  [INFO] Gluten Substrait ................................... SUCCESS [01:01 min]
18:00:32  [INFO] Gluten Celeborn .................................... SUCCESS [  4.345 s]
18:00:32  [INFO] Gluten Iceberg ..................................... FAILURE [  5.848 s]
18:00:32  [INFO] Gluten DeltaLake ................................... SKIPPED
18:00:32  [INFO] Gluten Package ..................................... SKIPPED
18:00:32  [INFO] Gluten Ras Planner ................................. SKIPPED
18:00:32  [INFO] Gluten Kafka ....................................... SKIPPED
18:00:32  [INFO] Gluten Backends ClickHouse ......................... SKIPPED
18:00:32  [INFO] Gluten Unit Test Parent ............................ SKIPPED
18:00:32  [INFO] Gluten Unit Test Common ............................ SKIPPED
18:00:32  [INFO] Gluten Unit Test ................................... SKIPPED
18:00:32  [INFO] ------------------------------------------------------------------------
18:00:32  [INFO] BUILD FAILURE
18:00:32  [INFO] ------------------------------------------------------------------------
18:00:32  [INFO] Total time:  03:49 min
18:00:32  [INFO] Finished at: 2026-01-06T02:00:32Z
18:00:32  [INFO] ------------------------------------------------------------------------
18:00:32  [WARNING] The requested profile "spark-3.2" could not be activated because it does not exist.
18:00:32  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.1:compile (default-compile) on project gluten-iceberg: Compilation failure
18:00:32  [ERROR] /home/jenkins/agent/workspace/gluten/gluten-ci/ut-stage-1/gluten-iceberg/src/main/java/org/apache/gluten/connector/write/MetricsWrapper.java:[21,25] error: cannot access Metrics
18:00:32  [ERROR]   bad class file: /root/.m2/repository/org/apache/iceberg/iceberg-spark-runtime-3.5_2.12/1.10.0/iceberg-spark-runtime-3.5_2.12-1.10.0.jar(org/apache/iceberg/Metrics.class)
18:00:32  [ERROR]     class file has wrong version 55.0, should be 52.0
18:00:32  [ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
18:00:32  [ERROR] 
18:00:32  [ERROR] -> [Help 1]

**Comment by zhouyuan** [comment]
@zzcclp could you please help to take a look?

**Comment by QCLyu** [comment]
Hi @zhouyuan @zzcclp Just following up on my last comment here. I’d love to get your thoughts on CI config issue—do you feel this makes sense, or maybe not? Want to make sure we’re aligned before I move forward.

**Comment by zzcclp** [comment]
Sorry for the late reply, I modified the CI script , please hava a try again.

File: .github/workflows/flink.yml [hunk 1]
```diff
@@ -61,7 +61,7 @@ jobs:
           sudo yum install https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/tzdata-2025a-1.el9.noarch.rpm -y
           sudo .github/workflows/util/install-flink-resources.sh
           git clone -b gluten-0530 https://github.com/bigo-sg/velox4j.git
-          cd velox4j && git reset --hard 430d149837b9311df2787797fe0e0ec9abefd688
+          cd velox4j && git reset --hard 59442932803ca06a34c1cdbc43a3b80348c4da7a
```
Comment (PHILO-HE) [inline .github/workflows/flink.yml]: Should this line be changed? It's separate for Flink Support, not related to Spark support.

File: .github/workflows/velox_backend_x86.yml
Comment (philo-he) [inline .github/workflows/velox_backend_x86.yml:1]: I assume we should only remove Spark 3.2 UT test jobs from CI. Other jobs like celeborn test should change to using Spark 3.3 or higher supported versions, instead of deleting those tests.

File: .idea/vcs.xml
Comment (philo-he) [inline .idea/vcs.xml:1]: Please confirm if these changes were intended.

**Review by PHILO-HE — COMMENTED** [review]
Thank you so much for your work. Some comments. Please check if they make sense.

Suggest to use `git pull --rebase <remote name> main` to rebase code. Otherwise, some commits already merged to main branch are included in this PR, which are mixed with your changes and not friendly to reviewers.

Please also clean the use of Spark 3.2 in build scripts under dev.

Maybe, some Spark shim APIs were introduced to adapt to the differences between Spark 3.2 and later Spark versions. If so, we should also remove them (can be done in separate PRs).

File: .idea/vcs.xml
Comment (QCLyu) [reply .idea/vcs.xml:1]: Thanks @PHILO-HE I'm working on it and will commit again.

File: .github/workflows/velox_backend_x86.yml
Comment (QCLyu) [reply .github/workflows/velox_backend_x86.yml:1]: Thanks @PHILO-HE Agreed. 
Also, created a linked issue for Spark 3.2-specific compatibility code removal: #11379

**Comment by QCLyu** [comment]
## Summary of most recent changes:
### Main deprecation commit (10bed0dd7 - "deprecate Spark-3.2")
#### Removed Spark 3.2 support:
- Deleted shims/spark32/ directory (entire Spark 3.2 shim module)
- Removed spark-3.2 from Maven profiles in pom.xml and gluten-ut/pom.xml
- Removed Spark 3.2 CI test jobs from .github/workflows/velox_backend_x86.yml:
- tpc-test-ubuntu-oom (Spark 3.2 specific)
- tpc-test-ubuntu-randomkill (Spark 3.2 specific)
- spark-test-spark32 (Spark 3.2 UT tests)
- spark-test-spark32-slow (Spark 3.2 slow tests)
- Removed spark-3.2 from build scripts:
- dev/buildbundle-veloxbe.sh
- dev/builddeps-veloxbe.sh
- dev/format-scala-code.sh
- dev/release/build-release.sh
- dev/release/package-release.sh
- dev/docker/Dockerfile.centos8-dynamic-build
- dev/docker/Dockerfile.centos9-dynamic-build
- Updated documentation to remove Spark 3.2 references

#### Updated (not deleted) — per reviewer feedback:
- tpc-test-centos8-uniffle job:
Changed from spark-3.2 → spark-3.3 in matrix
Updated commands to use spark-3.3
- tpc-test-ubuntu-2204-celeborn job:
Changed from spark-3.2 → spark-3.3 in matrix
Updated commands to use spark-3.3
- Test code updates:
backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala:
    * Removed isSparkVersionLE("3.2") check
    * Fixed Scalastyle line length issue
    
### CI fixes commit (0861158ae - "Fixed workflow paths")
- Fixed 4 CI failures in .github/workflows/velox_backend_x86.yml:
   Added SETUP environment variable (line 49):
   SETUP: 'source .github/workflows/util/setup-helper.sh'
- Fixed tpc-test-centos8-uniffle Maven path (line 406):
Changed: $MVN_CMD → $GITHUB_WORKSPACE/$MVN_CMD
- Fixed tpc-test-ubuntu-2204-celeborn setup (lines 439-440):
Changed: $SETUP install_maven → source .github/workflows/util/setup-helper.sh + install_maven
- Fixed tpc-test-ubuntu-2204-celeborn Maven path (line 467):
Changed: $MVN_CMD → $GITHUB_WORKSPACE/$MVN_CMD

**Comment by QCLyu** [comment]
Hi @zhouyuan @zzcclp @PHILO-HE , as this PR touches files that are frequently updated, such as velox_backend_x86.yml, do you think it's better to resolve all conflicts after the PR is approved, or maybe keep resolving conflicts while waiting for reviewers' feedback?

File: backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala [hunk 2]
```diff
@@ -92,9 +92,12 @@ class VeloxHashJoinSuite extends VeloxWholeStageTransformerSuite {
...
       val wholeStages = plan.collect { case wst: WholeStageTransformer => wst }
-      if (isSparkVersionLE("3.2")) {
-        assert(wholeStages.length == 1)
-      } else if (isSparkVersionGE("3.5")) {
+
+      if (
+        SparkShimLoader.getSparkVersion.startsWith("3.5.") ||
+        SparkShimLoader.getSparkVersion.startsWith("4.0.") ||
+        SparkShimLoader.getSparkVersion.startsWith("4.1.")
+      ) {
```
Comment (philo-he) [inline backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala:99]: Nit: suggest inverting the if check. Then when higher Spark versions are supported, no need to add conditions.
```scala
if (
        SparkShimLoader.getSparkVersion.startsWith("3.3.") ||
        SparkShimLoader.getSparkVersion.startsWith("3.4.")) {
        assert(wholeStages.length == 3)
      } else {
        assert(wholeStages.length == 5)
```

File: backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala [hunk 3]
```diff
@@ -74,7 +74,7 @@ class VeloxHashJoinSuite extends VeloxWholeStageTransformerSuite {
     }
   }
 
-  testWithMinSparkVersion("generate hash join plan - v2", "3.2") {
+  testWithMinSparkVersion("generate hash join plan - v2", "3.3") {
```
Comment (philo-he) [inline backends-velox/src/test/scala/org/apache/gluten/execution/VeloxHashJoinSuite.scala]: In the existing code, using `testWithMinSparkVersion` is redundant since the minimum supported Spark version prior to this PR was already 3.2. By switching to a standard `test()` call, we avoid the need for future updates when Spark 3.3 support is eventually dropped. Similarly, any use of `testWithMinSparkVersion("", 3.3)` can be simplified to `test()` in this PR.

File: .github/workflows/velox_backend_x86.yml [hunk 4]
```diff
@@ -603,17 +433,19 @@ jobs:
         run: |
           sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true
           sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true
-      - name: Setup java
+      - name: Setup java and maven
         run: |
           yum update -y && yum install -y java-1.8.0-openjdk-devel wget
+          source .github/workflows/util/setup-helper.sh
+          install_maven
```
Comment (philo-he) [inline .github/workflows/velox_backend_x86.yml]: Seems strange to install maven. I assume $MVN_CMD, i.e., build/mvn, will download mvn if it is not found in the build environment.

File: .github/workflows/velox_backend_x86.yml [hunk 5]
```diff
@@ -359,179 +356,12 @@ jobs:
...
-            -d=OFFHEAP_SIZE:1g,spark.memory.offHeap.size=1g \
-            -d=IO_THREADS:12,spark.gluten.sql.columnar.backend.velox.IOThreads=12 \
-            -d=IO_THREADS:0,spark.gluten.sql.columnar.backend.velox.IOThreads=0
-
-  tpc-test-ubuntu-randomkill:
-    needs: build-native-lib-centos-7
-    strategy:
-      fail-fast: false
-      matrix:
-        spark: [ "spark-3.2" ]
```
Comment (philo-he) [inline .github/workflows/velox_backend_x86.yml:482]: We may still need this test job. Please keep it with Spark version updated in this line.

File: .github/workflows/velox_backend_x86.yml [hunk 6]
```diff
@@ -359,179 +356,12 @@ jobs:
               --extra-conf=spark.gluten.ras.enabled=true 
           "
 
-  tpc-test-ubuntu-oom:
-    needs: build-native-lib-centos-7
-    strategy:
-      fail-fast: false
-      matrix:
-        spark: [ "spark-3.2" ]
```
Comment (philo-he) [inline .github/workflows/velox_backend_x86.yml:367]: ditto

File: .github/workflows/velox_backend_x86.yml [hunk 7]
```diff
@@ -198,27 +193,29 @@ jobs:
           $GITHUB_WORKSPACE/$MVN_CMD clean install -P${{ matrix.spark }} -P${{ matrix.java }}
           GLUTEN_IT_JVM_ARGS=-Xmx5G sbin/gluten-it.sh queries-compare \
             --local --preset=velox --benchmark-type=h --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
-          && GLUTEN_IT_JVM_ARGS=-Xmx6G sbin/gluten-it.sh queries-compare \
-            --local --preset=velox --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1
+          && if [ "${{ matrix.spark }}" = "spark-4.0" ]; then \
+               GLUTEN_IT_JVM_ARGS=-Xmx6G sbin/gluten-it.sh queries-compare \
+                 --local --preset=velox --benchmark-type=ds --error-on-memleak --off-heap-size=10g -s=1.0 --threads=16 --iterations=1 \
+                 --excluded-queries=q72; \
```
Comment (philo-he) [inline .github/workflows/velox_backend_x86.yml]: Curious why these changes are needed? Does the test failure for Spark 4.0 happen occasionally? Maybe, we can move it to a separate PR. We can ignore such failures if they are indeed not related to this PR.

File: docs/get-started/build-guide.md [hunk 8]
```diff
@@ -58,18 +58,17 @@ The below parameters can be set via `-P` for mvn.
 | delta               | Build Gluten with Delta Lake support. | disabled      |
 | iceberg             | Build Gluten with Iceberg support.    | disabled      |
 | hudi                | Build Gluten with Hudi support.       | disabled      |
-| spark-3.2           | Build Gluten for Spark 3.2.           | enabled       |
-| spark-3.3           | Build Gluten for Spark 3.3.           | disabled      |
-| spark-3.4           | Build Gluten for Spark 3.4.           | disabled      |
-| spark-3.5           | Build Gluten for Spark 3.5.           | disabled      |
+| spark-3.2           | Build Gluten for Spark 3.2.           | disabled      |
```
Comment (philo-he) [inline docs/get-started/build-guide.md]: This line can be removed.

File: docs/get-started/build-guide.md [hunk 9]
```diff
@@ -58,18 +58,17 @@ The below parameters can be set via `-P` for mvn.
...
+| spark-3.3           | Build Gluten for Spark 3.3.           | enabled       |
+| spark-3.4           | Build Gluten for Spark 3.4.           | enabled      |
+| spark-3.5           | Build Gluten for Spark 3.5.           | enabled      |
```
Comment (philo-he) [inline docs/get-started/build-guide.md:63]: Currently, spark-3.5 is enabled by default. So the others should be marked as disabled to indicate its default state.

File: .github/workflows/velox_backend_x86.yml (hunk 7 above)
Comment (QCLyu) [reply .github/workflows/velox_backend_x86.yml]: Thanks @PHILO-HE . The change was made to accommodate Spark 4.0 compatibility issues with q72. An issue was created for this problem: https://github.com/apache/incubator-gluten/issues/11363

Happy to remove the temporary workaround from this PR.

**Comment by QCLyu** [comment]
Thanks @PHILO-HE . I received your feedback and am making changes.

File: .github/workflows/velox_backend_x86.yml [hunk 10]
```diff
@@ -46,6 +46,7 @@ env:
   MVN_CMD: 'build/mvn -ntp'
   WGET_CMD: 'wget -nv'
   CCACHE_DIR: "${{ github.workspace }}/.ccache"
+  SETUP: 'source .github/workflows/util/setup-helper.sh'
```
Comment (philo-he) [inline .github/workflows/velox_backend_x86.yml]: Remove this line if not required.

File: docs/get-started/build-guide.md [hunk 11]
```diff
@@ -8,27 +8,27 @@ parent: Getting-Started
...
+| run_setup_script       | Run setup script to install Velox dependencies.                                               | ON      |
+| velox_repo             | Specify your own Velox repo to build.                                                         | ""      |
+| velox_branch           | Specify your own Velox branch to build.                                                       | ""      |
+| velox_home             | Specify your own Velox source path to build.                                                  | ""      |
+| build_velox_tests      | Build Velox tests.                                                                            | OFF     |
+| build_velox_benchmarks | Build Velox benchmarks (velox_tests and connectors will be disabled if ON)                    | OFF     |
+| build_arrow            | Build arrow java/cpp and install the libs in local. Can turn it OFF after first build.        | ON      |
+| spark_version          | Build for specified version of Spark(3.3, 3.4, 3.5, ALL). `ALL` means build for all versions. | ALL     |
```
Comment (philo-he) [inline docs/get-started/build-guide.md:31]: Could you update this line to include 4.0, 4.1?

**Review by PHILO-HE — APPROVED** [review]
Looks good. Just two minor comments. Thanks.

@zhouyuan, @zzcclp, do you have any comments?

**Comment by zhouyuan** [comment]
@QCLyu Thank you for your outstanding work and relentless iteration!

File: .github/workflows/velox_backend_x86.yml (hunk 10 above)
Comment (zhouyuan) [reply .github/workflows/velox_backend_x86.yml]: fixed

File: docs/get-started/build-guide.md (hunk 11 above)
Comment (zhouyuan) [reply docs/get-started/build-guide.md:31]: Will fix in another PR with doc updates for spark-4.0 update

**Comment by QCLyu** [comment]
Thanks @PHILO-HE @zhouyuan @zzcclp . That's very helpful.
